name: cdm
version: 0.0.0

dependencies:
  - daml-stdlib
  - record-hasfield

default-extensions:
  - DuplicateRecordFields
  - DisambiguateRecordFields
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -O0

library:
  source-dirs: src
