name: cdm
version: 0.0.0

dependencies:
  - daml-stdlib

default-extensions:
  - DuplicateRecordFields
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -O0

library:
  source-dirs: src
