resolver: lts-13.13
packages:
  - .
  - libs/daml-stdlib
extra-deps:
  - decimal-arithmetic-0.5.1.0
  - record-hasfield-1.0
  - time-1.9.2
  - directory-1.3.5.0
  - process-1.6.7.0
  - unix-2.7.2.2
allow-newer: True
