name: with-preprocessor
version: 0.0.0

dependencies:
  - base
  - hspec
  - hspec-megaparsec
  - megaparsec
  - text

library:
  source-dirs: src

executables:
  with-preprocessor:
    main: exe/Main.hs
    dependencies:
      - with-preprocessor
