# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: (Apache-2.0 OR BSD-3-Clause)
version: 2.1

jobs:
  daml:
    docker:
      - image: digitalasset/daml-sdk:0.11.23-circleci-master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install libtinfo
          command: apt-get update && apt-get install -y libtinfo-dev
      - run:
          name: Test Dar
          command: make test-dar
      - run:
          name: Build Dar
          command: make build-dar
      - run:
          name: Save test results
          command: |
            mkdir -pv ~/test-results/daml
            find . -type f -regex ".*/target/.*DarTests.xml" -exec cp {} ~/test-results/daml/ \;
      - store_test_results:
          path: ~/test-results
      - run:
          name: Install stack
          command: |
            curl -sSL https://get.haskellstack.org/ | sh
      - run:
          name: Generating Haskell
          command: |
            ./haskell/scripts/generate-haskell.sh
      - run:
          name: Run Haskell tests
          command: |
            cd haskell && stack test
workflows:
  Build and test:
    jobs:
      - daml
