# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
version: 2.1

jobs:
  daml:
    docker:
      - image: digitalasset/daml-sdk:0.13.46
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Dar
          command: |
            cd daml
            daml build
      - run:
          name: Test Dar
          command: |
            cd daml
            daml test --junit .daml/DarTests.xml
  haskell:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Generate Haskell
          command: |
            cd haskell
            ./scripts/generate-haskell.sh
      - run:
          name: Run tests
          command: |
            cd haskell && stack test

workflows:
  Build and test:
    jobs:
      - daml
      - haskell
